/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import coneccion.Conexion;
import controlador.ControladorLibros;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Blob;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Libro;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author User
 */
public class AgregarLibros extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarLibros
     */
    public AgregarLibros() {
        initComponents();
    }
    private String imagenPath;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFileChooser = new javax.swing.JFileChooser();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        JFileChooser.setAcceptAllFileFilterUsed(false);
        JFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        JFileChooser.setBackground(java.awt.Color.black);
        JFileChooser.setDialogTitle("Imagenes");
        JFileChooser.setFileFilter(null);
        JFileChooser.setPreferredSize(new java.awt.Dimension(800, 400));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 200, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 200, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 200, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 40));

        jLabel2.setText("Autor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 30));

        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 50, 30));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                        
    String nombre = jTextField1.getText();
    String autor = jTextField2.getText();
    String precioStr = jTextField3.getText();

    // Verifica que los campos no estén vacíos
    if (!nombre.isEmpty() && !autor.isEmpty() && !precioStr.isEmpty()) {
        try {
            double precio = Double.parseDouble(precioStr);

            // Crea un objeto Libro con los datos recopilados
            Libro libro = new Libro(0, nombre, autor, precio, 1);

            // Llama al método agregarLibro para insertar el libro en la base de datos
            ControladorLibros controladorLibros = new ControladorLibros();
            if (controladorLibros.agregarLibro(libro)) {
                System.out.println("Libro agregado a la base de datos.");
            } else {
                System.out.println("Error al agregar el libro a la base de datos.");
            }
        } catch (NumberFormatException e) {
            System.out.println("El precio no es válido. Ingrese un número válido para el precio.");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AgregarLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        System.out.println("Complete todos los campos antes de agregar el libro.");
    }


        
    


    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser JFileChooser;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables


}
