/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import coneccion.Conexion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class GestionLibros extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionLibros
     */
    public GestionLibros() {
        initComponents();
        this.CargarTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 381, 285));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
private void CargarTablaClientes() {
    DefaultTableModel modelo = new DefaultTableModel();

    try (Connection con = Conexion.conectar()) {
        if (con != null) {
            String sql = "SELECT * FROM libros";
            try (Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {

                modelo.addColumn("ID");
                modelo.addColumn("Nombre");
                modelo.addColumn("Autor");
                modelo.addColumn("Precio");
                modelo.addColumn("stock");

                while (rs.next()) {
                    Object[] fila = new Object[5];
                    for (int i = 0; i < 5; i++) {
                        fila[i] = rs.getObject(i + 1);
                    }

                    modelo.addRow(fila);
                }

                jTable1.setModel(modelo);
            }
        }
    } catch (SQLException e) {
        System.out.println("Error al llenar la tabla de clientes: " + e);
    }

    jTable1.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            int fila = jTable1.rowAtPoint(e.getPoint());
            int columna = 0; // Suponemos que la primera columna contiene el ID del cliente.

            if (fila > -1) {
                int idCliente = (int) modelo.getValueAt(fila, columna);
                EnviarDatosClientesSeleccionados(idCliente);
            }
        }
    });
}

private void EnviarDatosClientesSeleccionados(int idCliente) {
    try {
        Connection con = Conexion.conectar();
        String sql = "SELECT * FROM clientes WHERE id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, idCliente); // Establece el valor del parámetro en la consulta

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String nombre = rs.getString("nombre");
            String autor = rs.getString("autor");
            String precio = rs.getString("precio");

            // Actualiza los campos de texto con los datos del cliente seleccionado
            jTextField1.setText(nombre);
            jTextField2.setText(autor);
            jTextField3.setText(precio);
            
        }

        rs.close();
        pst.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

private int obtenerIdDeLaTabla() {
    int filaSeleccionada = jTable1.getSelectedRow(); // Obtén la fila seleccionada
    if (filaSeleccionada != -1) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int id = (int) modelo.getValueAt(filaSeleccionada, 0);
        return id;
    }
    return -1;
}
}

